# Generated by Django 3.2 on 2023-08-04 18:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 4, 18, 51, 23, 495036, tzinfo=utc)),
        ),
    ]
